name: bot approve
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  approve:
    if: |
      github.event.pull_request.user.login == github.repository_owner
      && ! github.event.pull_request.draft
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          review-message: "Auto approved automated PR 🚀"
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: test
        run: |
          ${{ github.event.pull_request.user.login }}
          ${{ github.repository_owner }}
          ${{ github.event.pull_request.draft }}
